import type { CurriculumLocale } from "@ai-sensei/curriculum";

/**
 * Command matching for board LaTeX (stage 2 of three).
 *
 * `flutter_math_fork` is a Dart port of KaTeX and cannot render everything the
 * original accepts. A command it cannot render reaches the device and that board
 * line becomes blank or throws. Losing one line mid-lesson is worse than being
 * slow, so commands are matched mechanically before sending.
 *
 * The three stages (`docs/pivot_plan_v1.md` §3-6):
 *
 *   | stage | where | what it prevents |
 *   | --- | --- | --- |
 *   | 1 formula templates | the prompt | wrong *combinations* of allowed commands |
 *   | 2 command matching | here | commands the port does not support |
 *   | 3 real KaTeX parse | backend/agent | broken syntax (unclosed braces, wrong arity) |
 *
 * Not done here:
 *   - character caps and the ban on multi-line environments (`align` etc.) are
 *     already rejected by `board.ts` in `@ai-sensei/contract`. Not implemented twice.
 *   - whether the syntax parses (stage 3's job). This module follows
 *     `packages/guardrail`'s promise of no side effects and no external
 *     dependencies, which is why KaTeX is not pulled in.
 *
 * Rejections are regenerated by the agent (prompt constraints plus a mechanical
 * check, guarding twice).
 */

/**
 * The allowed commands. Only what was actually rendered to PNG and inspected by
 * eye in the 2026-08-09 spike. The authoritative list is `docs/pivot_plan_v1.md` §3-6.
 *
 * Rule: add only what has been rendered and checked by eye. Never add something
 * "because it is in KaTeX's documentation" - that the port may not support it is
 * precisely why this layer exists. Loosen that and the guard means nothing.
 *
 * Unverified and therefore not yet included (to be added after measurement in late
 * W1 or W2): matrices of 3x3 or larger, `cases` with three or more rows.
 *
 * Measured and deliberately rejected (not merely unverified): the `\text` family
 * ({@link textCommands}) and `\overparen` (the arc symbol; in the 2026-08-12
 * measurement `flutter_math_fork` could not render it and it became "cannot
 * display formula". Write an arc as "arc AB" in `text`).
 *
 * Added 2026-08-12: there was not one geometry symbol, and geometry lessons lost
 * the whole board.
 *
 * In a lesson on "proving with the tangent-chord angle on a circumscribed circle",
 * the board showed only its heading and not one line. The cause was here: there
 * was no ∠, no △, no ∽ and no °. `\angle CAD = \angle ABC` failed with
 * `unknown_command`, and the repair failed on the same family. `board.ts` aborts
 * that whole explanation on a failed step, so one symbol ended the lesson.
 *
 * Geometry is a major area of high-school maths, and having nothing writable there
 * turned "stop unrenderable commands" into "stop a whole unit". The additions below
 * are only those actually rendered with `flutter_math_fork` on 2026-08-12 and
 * confirmed by eye (`\overparen` failed on the spot and is not included).
 */
export const allowedLatexCommands: ReadonlySet<string> = new Set([
  // Operators and relations
  "\\cdot",
  "\\leq",
  "\\geq",
  "\\neq",
  "\\pm",
  "\\times",
  "\\div",
  "\\mp",
  "\\approx",
  // An alternative spelling of `\leq`. Models write the short one routinely.
  // Rejecting something renderable over spelling wastes a whole repair round trip.
  "\\le",
  "\\ge",
  "\\ne",
  "\\lt",
  "\\gt",
  // Geometry. Its absence is what lost geometry units their whole board (above).
  "\\angle",
  "\\triangle",
  "\\perp",
  "\\parallel",
  // Similarity (∼) and congruence. Japanese textbooks use ∽ and ≡, English-speaking
  // ones ∼ and ≅, so both are included (choosing between notations is stage 1's job,
  // the prompt - the same split as `\binom`).
  "\\sim",
  "\\cong",
  "\\equiv",
  // Degrees (`90^\circ`). Appears in every geometry lesson as the unit of angle.
  "\\circ",
  // The implication arrow. Pushing the board's "⇒" into a text element splits the formula from its conclusion.
  "\\Rightarrow",
  "\\Leftrightarrow",
  // Sets (Math A, "sets and logic")
  "\\in",
  "\\notin",
  "\\subset",
  "\\supset",
  "\\cap",
  "\\cup",
  "\\emptyset",
  "\\varnothing",
  "\\infty",
  // Ellipsis. Appears in sequences and series as `a_1 + a_2 + \cdots + a_n`
  "\\cdots",
  "\\ldots",
  "\\dots",
  // Overline. Line segments, complex conjugates, means (`\bar{x}`)
  "\\overline",
  "\\bar",
  // Fractions and radicals (including `\sqrt[3]{}`'s optional argument)
  "\\frac",
  "\\cfrac",
  "\\sqrt",
  // Functions
  "\\sin",
  "\\cos",
  "\\tan",
  "\\log",
  // Natural log. Japanese textbooks write `\log_{e}`, but that is a notation choice
  // for stage 1 (the prompt); this layer only asks whether it renders (the same split
  // as `\binom`). Rendering confirmed 2026-08-12.
  "\\ln",
  // Sums, limits, integrals
  "\\sum",
  "\\lim",
  "\\to",
  "\\int",
  // Variable-size brackets used mid-computation in definite integrals,
  // `\Bigl[ x^3 + x^2 \Bigr]_0^1`. Plan §3-6b names this shape as one that actually
  // overflows the screen, so it will certainly appear.
  "\\Bigl",
  "\\Bigr",
  // Auto-sizing brackets. In the 2026-08-12 measurement `\left( \frac{a}{b} \right)`
  // stretched correctly. It is the form models write most naturally, and a round trip
  // rewriting it to `\Bigl` is not worth stopping the board (a step's worth of
  // silence). Broken support is caught by stage 3 (the real KaTeX parse).
  "\\left",
  "\\right",
  // Spacing. `\quad` is used when placing formulas side by side (simultaneous equations, etc.)
  "\\quad",
  // Binomial coefficients. Included as the standard notation in overseas curricula.
  // Japanese curricula use the textbook form `{}_{n}\mathrm{C}_{r}`, but that is
  // "which textbook to match", not "can it render". Choosing notation is stage 1's
  // job (the prompt); rejecting it here would cost English lessons an expression
  // (the flip side of holding back `\ln`).
  "\\binom",
  // Vectors
  "\\vec",
  "\\overrightarrow",
  // Typefaces. Required for the textbook forms {}_n\mathrm{P}_r / {}_n\mathrm{C}_r
  "\\mathrm",
  // Greek letters
  "\\theta",
  "\\alpha",
  "\\beta",
  "\\pi",
  // Logical connectives. Re-measured at the effective 340pt width (2026-08-09) and
  // ∴ / ∵ render. Japanese boards use them heavily, so emitting the symbols matters.
  "\\therefore",
  "\\because",
]);

/**
 * Single-character non-alphabetic commands. Tokenising with `\\[a-zA-Z]+` alone
 * misses them, and for the same reason they are easy to miss when building the
 * allow-list.
 *
 * - `\,` thin space (around sums and integrals)
 * - `\ ` escaped space (separating a list like `\sin\theta,\ \cos\theta`)
 * - `\{` `\}` set braces
 *
 * The line separator `\\` is deliberately absent: whether it is allowed depends on
 * context and is judged separately (see how {@link checkBoardLatex} handles `\\`
 * and `&`).
 */
export const allowedLatexSymbolCommands: ReadonlySet<string> = new Set([
  "\\,",
  "\\ ",
  "\\{",
  "\\}",
]);

/**
 * The allowed environments: matrices and case analysis only.
 * Multi-line environments such as `align` are rejected earlier on the contract side
 * (`board.ts`'s `tex`), so they should never reach here - but this still fails
 * correctly on its own (guardrail does not depend on contract and must not assume
 * the other side's checks).
 */
export const allowedLatexEnvironments: ReadonlySet<string> = new Set(["pmatrix", "cases"]);

/**
 * Commands that put prose inside a formula. They are absent from the allow-list, so
 * they would fail as `unknown_command` anyway, but they get their own reason.
 *
 * Why:
 *   1. It is the form the LLM most wants. Putting "therefore", "hence" or "because"
 *      on the board naturally suggests `\text{}`, so it arrives often.
 *   2. It is not a ban but a wrong location. A line of Japanese already has a home
 *      in contract's `{ kind: "text", body }`. A repair instruction that ends at
 *      "do not use it" makes the LLM flee to another form such as
 *      `\mathrm{よって}` and loop forever. The separate reason exists to say where
 *      it should go.
 *
 * Measured 2026-08-09: the "よって" in `\text{よって}\ x=2` rendered as four black
 * bars (tofu), because KaTeX's font (`KaTeX_Main`) has no Japanese glyphs. That was
 * in the widget test environment, and on a real device it might fall back to the
 * system font. It stays banned anyway: whether a device fixes it is unverified, and
 * even if it did, with a `text` element available there is no reason to put
 * Japanese in a formula block.
 */
const textCommands: ReadonlySet<string> = new Set([
  "\\text",
  "\\textrm",
  "\\textbf",
  "\\textit",
  "\\textsf",
  "\\texttt",
  "\\mbox",
]);

/**
 * Kana, kanji and full-width symbols. They break the same way without any command,
 * so the whole `tex` is checked. `\mathrm{よって}` and a bare `よって` garble for the
 * same reason (the font lacks the glyphs); listing command names cannot close it.
 */
const japaneseCharacters = /[　-〿぀-ヿ一-鿿＀-ﾟ]/;

export const latexRejectionReasons = [
  /** A command whose support in the port is unconfirmed. */
  "unknown_command",
  /** Prose or Japanese inside a formula (its home is contract's `text` element). */
  "text_in_math",
  /** A disallowed environment (`align` etc.). */
  "unknown_environment",
  /** `\begin` and `\end` do not match. */
  "unbalanced_environment",
  /** `\\` (line break) or `&` (column separator) used outside an environment. */
  "row_separator_outside_environment",
] as const;
export type LatexRejectionReason = (typeof latexRejectionReasons)[number];

export type LatexVerdict =
  | { ok: true }
  | { ok: false; reason: LatexRejectionReason; detail: string };

/**
 * Token extraction.
 *
 * Four kinds in one pattern:
 *   1. `\begin{pmatrix}` / `\end{cases}` - entering and leaving an environment
 *   2. alphabetic commands such as `\frac`
 *   3. single-character non-alphabetic commands such as `\,` `\{` `\\`
 *      (not caught by `\\[a-zA-Z]+`)
 *   4. `&` - the column separator. Not a command, but it must not sit outside an
 *      environment
 *
 * Braces, digits and bare letters (variables) are ignored. This handles command
 * matching only.
 */
const LATEX_TOKEN = /\\(begin|end)\{([^}]*)\}|\\([a-zA-Z]+)|\\([^a-zA-Z])|(&)/g;

/**
 * Checks one formula destined for the board.
 *
 * `\\` (line break) and `&` (column separator) are allowed only inside an
 * environment. Allowing them unconditionally is necessary or every `pmatrix` /
 * `cases` fails, but a `\\` outside an environment is an instruction to split "one
 * board line" into two, breaking §3-1's "one step = one line" and the screen
 * stacking built on it. contract bans multi-line environments, but a bare `\\`
 * passes through, so that hole is closed here (the nearest layer with no
 * overlapping responsibility).
 *
 * Broken environment matching is rejected too: we could no longer track whether we
 * are inside one, losing the very basis for judging `\\` (surveying broken syntax
 * exhaustively is stage 3's job, and this is not a substitute).
 */
export function checkBoardLatex(tex: string): LatexVerdict {
  // Checked before commands. Inside an allowed command's argument, as in
  // `\mathrm{よって}`, token matching alone would let it through.
  const japanese = tex.match(japaneseCharacters);
  if (japanese !== null) {
    return {
      ok: false,
      reason: "text_in_math",
      detail: `数式の中の日本語は表示できません(文字化けします): ${japanese[0]}`,
    };
  }

  const openEnvironments: string[] = [];

  for (const match of tex.matchAll(LATEX_TOKEN)) {
    const [, beginOrEnd, environment, command, symbol, ampersand] = match;

    if (beginOrEnd !== undefined && environment !== undefined) {
      if (!allowedLatexEnvironments.has(environment)) {
        return {
          ok: false,
          reason: "unknown_environment",
          detail: `描画を確認していない環境: ${environment}`,
        };
      }
      if (beginOrEnd === "begin") {
        openEnvironments.push(environment);
        continue;
      }
      if (openEnvironments.pop() !== environment) {
        return {
          ok: false,
          reason: "unbalanced_environment",
          detail: `\\end{${environment}} に対応する \\begin がありません`,
        };
      }
      continue;
    }

    if (command !== undefined) {
      if (textCommands.has(`\\${command}`)) {
        return {
          ok: false,
          reason: "text_in_math",
          detail: `数式の中に文章を置くコマンド: \\${command}`,
        };
      }
      if (!allowedLatexCommands.has(`\\${command}`)) {
        return {
          ok: false,
          reason: "unknown_command",
          detail: `描画を確認していないコマンド: \\${command}`,
        };
      }
      continue;
    }

    // `\\` (row separator) and `&` (column separator). Meaningful only inside an environment.
    const isRowSeparator = symbol === "\\" || ampersand !== undefined;
    if (isRowSeparator) {
      if (openEnvironments.length === 0) {
        return {
          ok: false,
          reason: "row_separator_outside_environment",
          detail:
            symbol === "\\"
              ? "環境の外の改行(\\\\)は使えません。板書は1手順=1行です"
              : "環境の外の列区切り(&)は使えません",
        };
      }
      continue;
    }

    if (symbol !== undefined && !allowedLatexSymbolCommands.has(`\\${symbol}`)) {
      return {
        ok: false,
        reason: "unknown_command",
        detail: `描画を確認していないコマンド: \\${symbol}`,
      };
    }
  }

  if (openEnvironments.length > 0) {
    return {
      ok: false,
      reason: "unbalanced_environment",
      detail: `\\end{${openEnvironments[openEnvironments.length - 1]}} が閉じられていません`,
    };
  }

  return { ok: true };
}

/**
 * For inspecting what the check saw (tests and logs).
 * The verdict itself belongs to {@link checkBoardLatex}; this only reports what was in there.
 */
export function collectLatexCommands(tex: string): string[] {
  const commands: string[] = [];
  for (const match of tex.matchAll(LATEX_TOKEN)) {
    const [, beginOrEnd, environment, command, symbol] = match;
    if (beginOrEnd !== undefined) commands.push(`\\${beginOrEnd}{${environment}}`);
    else if (command !== undefined) commands.push(`\\${command}`);
    else if (symbol !== undefined) commands.push(`\\${symbol}`);
  }
  return commands;
}

/**
 * The instruction attached to the regeneration prompt. Written in the
 * conversation's language (mixing a Japanese instruction into an English lesson
 * makes only the next board come back in Japanese).
 *
 * The wording says what to fix, not just why - given only a reason, the LLM
 * re-emits the same formula.
 *
 * Every instruction must point at the `text` element. Ending at "write what cannot
 * be expressed in Japanese" makes the LLM write `\text{よって}` and fail with
 * `text_in_math` on the next turn. Instructions that cycle make regeneration spin,
 * so anything that cannot be a formula is always sent to "put it on the board as `text`".
 */
export const latexRejectionGuidanceByLocale: Record<
  CurriculumLocale,
  Record<LatexRejectionReason, string>
> = {
  ja: {
    unknown_command:
      "その記号は板書に表示できません。基本のコマンド(\\frac \\sqrt \\sum \\int \\vec \\mathrm など)だけで式を書き直すこと。式にできない説明は、数式に混ぜず text の板書として送ること。",
    text_in_math:
      "数式の中に日本語や文章を入れないこと(文字化けします)。「よって」のような一行は、数式ではなく text の板書として送ること。",
    unknown_environment:
      "使える環境は pmatrix(行列)と cases(場合分け)だけ。ほかの環境は使わないこと。",
    unbalanced_environment: "\\begin と \\end を必ず対で書くこと。",
    row_separator_outside_environment:
      "1つの板書は1行。改行(\\\\)を入れず、式を分けたいときは手順を2つに分けること。",
  },
  en: {
    unknown_command:
      "That symbol cannot be drawn on the board. Rewrite the formula using only the basic commands (\\frac, \\sqrt, \\sum, \\int, \\vec, \\mathrm). Anything that cannot be written as a formula goes in a text board element, not in the LaTeX.",
    text_in_math:
      "Do not put words inside a formula. Send a line of prose as a text board element, not as LaTeX.",
    unknown_environment:
      "The only environments available are pmatrix (matrices) and cases. Do not use any other.",
    unbalanced_environment: "Always pair \\begin with \\end.",
    row_separator_outside_environment:
      "One board line per step. Do not use \\\\ — split it into two steps instead.",
  },
};

/** The default (no locale given) is the Japanese wording. */
export const latexRejectionGuidance: Record<LatexRejectionReason, string> =
  latexRejectionGuidanceByLocale.ja;
